### ISSUE TITLE
BC introduced by ZF 2.4

### ISSUE THREAD

**Issue by leogr** [ripaclub/sphinxsearch#36]
Some method signatures have been [changed](https://github.com/zendframework/zf2/commit/c518cc2f85745c997b4be89035507e58cc054d52) in ZF 2.4.

The library must be fixed. 

Side question: does it make sense to introduce a polyfill to maintain legacy compatibility with old ZF series (i.e. < 2.4.0)?

**Comment by leodido** [comment]
I think it makes sense to introduce a polyfill to maintain compatibility with ZF >= 2.2.
This wat existing users could upgrade to upcoming 0.8.0 version. 

Otherwise existing users of this library (we have 5K total downloads and ~400 per month) will have to bock their composer dependence to the 0.7.0 and use 2.2/2.3 versions of ZF libraries that sphinxsearch uses.

**Comment by leodido** [comment]
However I suggest a new branch `feature/ZF2.4` to start implementation, fixes and polyfill.

**Comment by leogr** [comment]
:+1: 

However, polyfill could be hard to test and may introduce autoloading issues.

**Comment by leodido** [comment]
We have to think about it a moment longer.

**Comment by leogr** [comment]
Here https://github.com/ripaclub/sphinxsearch/commit/d980ac85708febddb522166caec19cead854fa90 I introduced a simple polyfill that can handle legacy version from ZF 2.1.x and fixes BCs introduced in ZF 2.4.x.

I think that should work fine for now, but also it should be removed in next major version because it will be very hard to mantain unit test compatibility if new features are introduced.

So we could tag this patch as 0.7.1, then in 0.8.x we could remove it and also we can consider to remove the PHP 5.3.x compatibility in order use traits (introduced in PHP 5.4.0)

**Comment by leodido** [comment]
I propose to move this commit to another branch (e.g., legacy/zf). Then we tag on this new branch this patch differently (e.g., 0.7.0-legacy).

For the future mainstream release I totally agree: 
PHP5.4
ZF2.4
